// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCROG_lShwboNI3y_6-4_uUUU7gsrnCPsk',
    appId: '1:873150696450:web:9ea984d37d0eb08b0aab1b',
    messagingSenderId: '873150696450',
    projectId: 'csia-52866',
    authDomain: 'csia-52866.firebaseapp.com',
    storageBucket: 'csia-52866.firebasestorage.app',
    measurementId: 'G-ZPKC3CWMZS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-4gjhSZe38okt4hU1l4_kMQVIpxFcIqE',
    appId: '1:873150696450:android:f6bb3d182106186e0aab1b',
    messagingSenderId: '873150696450',
    projectId: 'csia-52866',
    storageBucket: 'csia-52866.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8x3PizmMe12-8ZSNTyEGyIlKsAkZKp8s',
    appId: '1:873150696450:ios:fab7c9d8804c6b710aab1b',
    messagingSenderId: '873150696450',
    projectId: 'csia-52866',
    storageBucket: 'csia-52866.firebasestorage.app',
    iosBundleId: 'com.example.testFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8x3PizmMe12-8ZSNTyEGyIlKsAkZKp8s',
    appId: '1:873150696450:ios:fab7c9d8804c6b710aab1b',
    messagingSenderId: '873150696450',
    projectId: 'csia-52866',
    storageBucket: 'csia-52866.firebasestorage.app',
    iosBundleId: 'com.example.testFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCROG_lShwboNI3y_6-4_uUUU7gsrnCPsk',
    appId: '1:873150696450:web:82e550cfa466f4700aab1b',
    messagingSenderId: '873150696450',
    projectId: 'csia-52866',
    authDomain: 'csia-52866.firebaseapp.com',
    storageBucket: 'csia-52866.firebasestorage.app',
    measurementId: 'G-ZCS7LEDH4T',
  );

}